import { HashMap } from "./hashmap.js";
const test = new HashMap(); // or HashMap() if using a factory
test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
test.set("frog", "green");
test.set("grape", "purple");
test.set("hat", "black");
test.set("ice cream", "white");
test.set("jacket", "blue");
// test.set("kite", "pink");
// test.set("lion", "golden");
// test.set("lion", "silver");
// test.set("cat", "black");
// test.set("horse", "white");
console.log(test.get("apple"));
console.log(test.get("banana"));
console.log(test.has("apple"));
console.log(test.has("carot"));
console.log(test.keys());
console.log(test.values());
console.log(test.entries());
console.log(test.length());
console.log(test.clear());
test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
console.log(test.length());
console.log(test.keys());
console.log(test.values());
