import { HashMap } from "./hashmap.js";
import { HashSet } from "./hashset.js";

const test = new HashMap();
const hset = new HashSet();

test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
test.set("frog", "green");
test.set("grape", "purple");
// test.set("hat", "black");
// test.set("ice cream", "white");
// test.set("jacket", "blue");
// test.set("kite", "pink");
// test.set("lion", "golden");
// test.set("lion", "silver");
// test.set("cat", "black");
// test.set("horse", "white");

// console.log(test.get("apple"));
// console.log(test.get("banana"));
// console.log(test.has("apple"));
// console.log(test.has("carot"));
// console.log(test.keys());
// console.log(test.values());
console.log(test.entries());
console.log(test.length());
test.remove("banana");
test.remove("ba");
console.log(test.entries());
console.log(test.length());
// console.log(test.clear());
test.set("apple", "newred");
test.set("banana", "newyellow");
test.set("frog", "newgreen");
test.set("grape", "newpurple");
console.log(test.length());
// test.set("carrot", "orange");
// test.set("dog", "brown");
// test.set("elephant", "gray");
// console.log(test.length());
// console.log(test.keys());
// console.log(test.values());
// console.log(test.entries());

console.log("********");
console.log("HastSet: ");
console.log("********");
hset.add("sony");
hset.add("samsung");
hset.add("sega");
console.log(hset.has("sony"));
console.log(hset.has("so"));
console.log(hset.length());
console.log(hset.remove("sony"));
console.log(hset.length());
console.log(hset.keys());
